import { nodesOfKind, type ResourceGraph } from "../graph/types.js";
import type { RenderedFile } from "./types.js";

// Renders a hardened Caddyfile: auto-TLS, HSTS + security headers, and routes
// derived from each service's declared routes. Caddy is the only internet-facing
// process (guardrail enforced in compose + firewall).
export function renderCaddy(graph: ResourceGraph): RenderedFile {
  const services = nodesOfKind(graph, "service");

  const headers = `	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "strict-origin-when-cross-origin"
		-Server
	}`;

  const routes = services
    .map((svc) => {
      const name = svc.id.split(":")[1] ?? "svc";
      const decl = (svc.attrs.routes as string[] | undefined) ?? [];
      const paths = decl.map((r) => r.split(/\s+/, 2)[1]).filter(Boolean) as string[];
      const matcher = paths.length ? `@${name} path ${paths.map((p) => `${p}*`).join(" ")}` : "";
      return matcher
        ? `\t${matcher}\n\thandle @${name} {\n\t\treverse_proxy ${name}:8080\n\t}`
        : `\thandle_path /${name}/* {\n\t\treverse_proxy ${name}:8080\n\t}`;
    })
    .join("\n\n");

  const content = `# GENERATED by @ansi2u/harness-doctl
# SITE_DOMAIN is injected from the deployment's protected .env file.
{$SITE_DOMAIN} {
	encode gzip zstd
${headers}

	# Request-size guard limits trivial memory/disk exhaustion. Network-level rate
	# limiting belongs at the firewall or a custom Caddy build with caddy-ratelimit.
	request_body {
		max_size 10MB
	}

${routes || "\t# no HTTP services declared"}

	# auth + REST (present when declared)
	handle_path /auth/* {
		reverse_proxy gotrue:9999
	}
	handle_path /rest/* {
		reverse_proxy postgrest:3000
	}
}
`;

  return { path: "Caddyfile", content };
}
