import { nodesOfKind, type ResourceGraph } from "../graph/types.js";
import type { RenderedFile, RenderOpts } from "./types.js";

// Renders the OpenTofu root module that wires the ../../modules together for one
// project. Modules: vpc, volume (only if a DB is declared), droplet, firewall,
// spaces (one per bucket). See modules/README.md.
export function renderTofu(graph: ResourceGraph, opts: RenderOpts): RenderedFile[] {
  const project = graph.project;
  const buckets = nodesOfKind(graph, "object_storage");
  const hasDb = nodesOfKind(graph, "postgres").length > 0;

  const volumeModule = hasDb
    ? `
module "data_volume" {
  source   = "./modules/volume"
  name     = "${project}-data"
  region   = var.region
  size_gib = var.data_volume_gib
}
`
    : "";
  const volumeIds = hasDb ? "[module.data_volume.id]" : "[]";
  const dataVolumeName = hasDb ? `${project}-data` : "";

  const main = `# GENERATED by @ansi2u/harness-doctl — do not edit by hand.
# project: ${project}

terraform {
  backend "s3" {}
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

provider "digitalocean" {
  token             = var.do_token
  spaces_access_id  = var.spaces_access_id
  spaces_secret_key = var.spaces_secret_key
}

module "network" {
  source = "./modules/vpc"
  name   = "${project}"
  region = var.region
}
${volumeModule}
module "droplet" {
  source            = "./modules/droplet"
  name              = "${project}"
  region            = var.region
  size              = var.droplet_size
  vpc_uuid          = module.network.vpc_uuid
  ssh_key_ids       = var.ssh_key_ids
  ssh_public_keys   = var.ssh_public_keys
  headscale_url     = var.headscale_url
  tailscale_authkey = var.tailscale_authkey
  volume_ids        = ${volumeIds}
  data_volume_name  = "${dataVolumeName}"
}

module "firewall" {
  source          = "./modules/firewall"
  name            = "${project}"
  droplet_id      = module.droplet.id
  allow_ssh_cidrs = var.allow_ssh_cidrs
}
${buckets.map((b) => bucketModule(project, b.id)).join("\n")}
`;

  const variables = `variable "do_token" {
  type      = string
  sensitive = true
}

variable "spaces_access_id" {
  type    = string
  default = ""
}

variable "spaces_secret_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "region" {
  type    = string
  default = "${opts.region}"
}

variable "droplet_size" {
  type    = string
  default = "s-2vcpu-4gb"
}

variable "ssh_key_ids" {
  type    = list(string)
  default = []
}

variable "ssh_public_keys" {
  type    = list(string)
  default = []
}

variable "headscale_url" {
  type = string
}

variable "tailscale_authkey" {
  type      = string
  sensitive = true
  default   = ""
}

variable "allow_ssh_cidrs" {
  type    = list(string)
  default = []
}

variable "data_volume_gib" {
  type    = number
  default = 50
}
`;

  const outputs = `output "droplet_id" {
  value = module.droplet.id
}

output "droplet_ipv4" {
  value = module.droplet.ipv4
}

output "droplet_private_ip" {
  value = module.droplet.ipv4_private
}

output "tailnet_host" {
  value = module.droplet.tailnet_host
}
${buckets.map((b) => bucketOutput(b.id)).join("\n")}`;

  return [
    { path: "tofu/main.tf", content: main },
    { path: "tofu/variables.tf", content: variables },
    { path: "tofu/outputs.tf", content: outputs },
  ];
}

function bucketModule(project: string, nodeId: string): string {
  const name = nodeId.split(":")[1] ?? "bucket";
  return `
module "bucket_${name}" {
  source = "./modules/spaces"
  name   = "${project}-${name}"
  region = var.region
  acl    = "private" # guardrail: private by default
}`;
}

function bucketOutput(nodeId: string): string {
  const name = nodeId.split(":")[1] ?? "bucket";
  return `
output "bucket_${name}_domain" {
  value = module.bucket_${name}.domain
}`;
}
