/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: b9081202f6bcd9d1eb726d0fbb3fd805)
interface __BaseEnv_Env {
	WORKSPACES: R2Bucket;
	DB: D1Database;
	DISPATCHER: DispatchNamespace;
	RUN_QUEUE: Queue;
	RUN_RATE_LIMITER: RateLimit;
	ENVIRONMENT: string;
	PLATFORM_HOST: string;
	ALLOWED_ORIGINS: string;
	LEGACY_SWARM: string;
	DISPATCH_NAMESPACE: string;
	Mediator: DurableObjectNamespace /* MediatorAgent */;
	DomainAgent: DurableObjectNamespace /* DomainAgent */;
	Sandbox: DurableObjectNamespace /* Sandbox */;
	SwarmRuntime: DurableObjectNamespace /* SwarmRuntime */;
	CREW_WORKFLOW: Workflow /* CrewRunWorkflow */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PLATFORM_HOST" | "ALLOWED_ORIGINS" | "LEGACY_SWARM" | "DISPATCH_NAMESPACE">> {}
}
